language: julia
dist: trusty
sudo: true
os:
  - linux
  # - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
env:
  - DOCUMENTER_DEBUG="true" CONDA_JL_VERSION="2" PYTHON=""
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("PlanB")'
  - julia -e 'Pkg.test("PlanB", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("PlanB")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PlanB")); include(joinpath("docs", "make.jl"))'
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
